"""init

Revision ID: 59d4b80eb37e
Revises: 
Create Date: 2026-03-23 17:37:22.406134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59d4b80eb37e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('functions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_version', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.Enum('PYTHON', name='languageenum'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('function_handlers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('function_id', sa.BigInteger(), nullable=False),
    sa.Column('project_version', sa.BigInteger(), nullable=False),
    sa.Column('function_path', sa.String(), nullable=False),
    sa.Column('function_name', sa.String(), nullable=False),
    sa.Column('memory_size', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('s3_functions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('events', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('suffix', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['functions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s3_functions')
    op.drop_table('function_handlers')
    op.drop_table('functions')
    op.drop_table('projects')
    # ### end Alembic commands ###
