
server {
    listen 80;
    server_name localhost;
    client_max_body_size 64M;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/code/ {
        proxy_pass http://code-service:8001;
    }

    location /api/events/ {
        proxy_pass http://events-service:8002;
    }

    location /api/execution/ {
        proxy_pass http://execution-service:8003;
    }

}
